#!/usr/bin/env bash

vulcan build -v -s `pwd`/sw -p /tmp/sw/usr -c "
  mkdir -p /tmp/sw/usr &&
  dpkg-deb -X rsync_3.0.7-1ubuntu1.1_amd64.deb /tmp/sw/rsync &&
  dpkg-deb -X libuuid1_2.17.2-0ubuntu1.10.04.2_amd64.deb /tmp/sw/libuuid1 &&
  dpkg-deb -X uuid-dev_2.17.2-0ubuntu1.10.04.2_amd64.deb /tmp/sw/uuid-dev &&
  /tmp/sw/rsync/usr/bin/rsync -vvaP /tmp/sw/libuuid1/usr/ /tmp/sw/usr/ &&
  /tmp/sw/rsync/usr/bin/rsync -vvaP /tmp/sw/libuuid1/lib/ /tmp/sw/usr/lib/ &&
  /tmp/sw/rsync/usr/bin/rsync -vvaP /tmp/sw/uuid-dev/usr/ /tmp/sw/usr/ &&
  rm /tmp/sw/usr/lib/libuuid.so &&
  (
    cd /tmp/sw/usr/lib &&
    ln -vnfs libuuid.so.1.3.0 libuuid.so
  ) &&
  (
    cd zeromq-2.1.10 &&
    ./configure --help &&
    ./configure CPPFLAGS=-I/tmp/sw/usr/include LDFLAGS=-L/tmp/sw/usr/lib --prefix=/tmp/sw/usr &&
    make install
  ) &&
  find &&
  find /tmp/sw
"

tar ztvf /tmp/sw.tgz
